server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false   # ❌ disable config server (for now)

    gateway:
      routes:
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments,/appointments/**

        - id: doctor-service
          uri: http://localhost:8081
          predicates:
            - Path=/doctors,/doctors/**



# 🔥 Zipkin + Tracing
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans